#!/bin/bash

set -e -o pipefail

#++++                  This script is modified from:              ++++
#++++                        mitoVGP v2.2                         ++++
#++++ The Vertebrate Genomes Project Mitogenome Assembly Pipeline ++++
#++++     Credit: Giulio Formenti gformenti@rockefeller.edu       ++++
#++++	Modified by Amanda Stahlke amanda.stahlke@usda.gov        ++++

##### mitoVGP dir for ag100pest added here
mitoVGPdir=/project/ag100pest/software/modified_mitoVGP

if [ -z $1 ]; then

	echo "use $0 -h for help"
	exit 0;
elif [ $1 == "-h" ]; then

	cat << EOF

	Usage: '$0  -i species_ID -r reference -t threads'

	mitoVGP is used for reference-guided de novo mitogenome assembly using a combination of long and short read data.
	
	An existing reference from closely to distantly related species is used to identify mito-like reads in pacbio WGS data,
	which are then employed in de novo genome assembly. The assembly is further polished using both long and short read data,
	and linearized to start with the conventional Phenylalanine tRNA sequence.
	
	Check the github page https://github.com/GiulioF1/mitoVGP for a description of the pipeline.
	A complete Conda environment with all dependencies is available to run the pipeline in the same github page.
	
	This script a simple wrapper of the scripts found in the scripts/ folder. You can find more information
	on each step in the help (-h) of each script.

	Required arguments are:
		-a long read sequencing platform (Pacbio/ONT)
		-i a species ID (e.g. bCalAnn1)
		-r the reference sequence fasta file
		-t the number of threads
	
	Optional arguments are:
		-g the putative mitogenome size (potentially, that of the reference genome). If not provided, length of reference is used.
		   It does not need to be precise. Accepts Canu formatting.
		-1 use pacbio/nanopore reads from list of files, requires absolute path
		-2 use PE illumina reads from list of files (with fw and rv reads including R1/R2 in their names), requires absolute path
		-m the aligner (blasr|minimap2|pbmm2). Default is pbmm2
		-f filter reads by size prior to assembly (reduces the number of NUMT reads and helps the assembly) default 20000 or 1.5*reference size, whichever is larger
		-p filter reads by percent coverage of the reference over their length (avoid noise in the assembly when low coverage)
		-o the options for Canu
		-v picard validation stringency (STRICT/LENIENT default: STRICT)
		-z increase sensitivity of mummer overlap detection
		-b use gcpp or variantCaller during arrow polishing for 2.0 or earlier chemistry respectively (gcpp/variantCaller default: gcpp)

EOF

exit 0

fi

#set options

while getopts ":a:i:r:g:t:1:2:m:f:o:n:v:p:z:b:" opt; do

	case $opt in
		a)
			PLATFORM="$OPTARG"
			;;
        i)
        	ID="$OPTARG"
            ;;
        r)
			REF="$OPTARG"
			;;
		g)
			GSIZE="$OPTARG"
            ;;
		t)
			NPROC="$OPTARG"
            ;;
		1)
			READ1="$OPTARG"
			;;
		2)
			IL="$OPTARG"
			;;
		m)
			ALN="$OPTARG"
			;;
		f)
            FL="$OPTARG"
			;;
		n)
            CONTIG="$OPTARG"
			;;
		v)
            VAL="$OPTARG"
			;;
		p)
            PER="$OPTARG"
			;;
		z)
            SEN="$OPTARG"
			;;
		b)
			CAL="$OPTARG"
            ;;
		o)
            OPTS="$OPTARG"
			;;
		\?)
			echo "ERROR - Invalid option: -$OPTARG" >&2
			exit 1
			;;
	esac

done

printf "\n\n++++                 modified  mitoVGP v2.0                  ++++\n"

printf "\nStarted at at: $(date "+%Y-%m-%d %H-%M-%S")\n"
printf "\nWith command:\n"
printf "\n${0}\n"

#define working directory
W_URL=${ID}/assembly_MT_rockefeller/intermediates

if ! [[ -e "${W_URL}" ]]; then

	mkdir -p ${W_URL}

fi

#create log folder
if ! [[ -e "${W_URL}/log" ]]; then

	mkdir ${W_URL}/log

fi

#create reference folder
if ! [[ -e "${W_URL}/reference" ]]; then
	
	mkdir ${W_URL}/reference

fi

#copy the user-provided reference mitogenome to the reference folder
filename=$(basename -- "${REF}")
filename="${filename%.*}"

printf "\nUsing '${REF}' as reference\n"
cp ${REF} ${W_URL}/reference/${filename}.fasta

if [[ -z  ${GSIZE} ]]; then
	
	GSIZE=$(awk 'BEGIN {FS="\t"} $0 !~ ">" {sum+=length($0)} END {print sum}' ${W_URL}/reference/${filename}.fasta)
	
	printf "\nGenome size not provided, using reference genome size: ${GSIZE} bp\n"

	if [[ -z  ${FL} ]]; then
	declare -i DEF_FL=20000  # filter reads longer than this default
	AUTO_FL=$(python -c "print(round(1.5*$GSIZE))") # unless 1.5*reference size is larger
		if ["$DEF_FL" -gt "$AUTO_FL"];then
			FL=$DEF_FL
		else
			FL=$AUTO_FL
		fi
	printf "\nWill filter reads longer than $FL \n"
	fi
fi

if ! [[ -z  ${PLATFORM} ]]; then

	SCRIPT1_OPTS="${SCRIPT1_OPTS}-a ${PLATFORM} "

fi


if ! [[ -z  ${FL} ]]; then

	SCRIPT1_OPTS="${SCRIPT1_OPTS}-f ${FL} "

fi

if ! [[ -z  ${ALN} ]]; then

	SCRIPT1_OPTS="${SCRIPT1_OPTS}-m ${ALN} "

fi

if ! [[ -z  ${PER} ]]; then

	SCRIPT1_OPTS="${SCRIPT1_OPTS}-p ${PER} "

fi

if ! [[ -z  ${READ1} ]]; then

	SCRIPT1_OPTS="${SCRIPT1_OPTS}-1 ${READ1} "

fi

if ! [[ -z  ${OPTS} ]]; then
	
	OPTS="${OPTS//\ /_}"
	
	SCRIPT1_OPTS="${SCRIPT1_OPTS}-o ${OPTS} "

fi


printf "\nWill use '${IL}' for short read polishing\n"



#retrieve mito-like reads and assemble
printf "\nCommand: sh -e $mitoVGPdir/scripts/01_mtDNApipe -s ${SPECIES} -i ${ID} -r ${filename}.fasta -g ${GSIZE} -t ${NPROC} ${SCRIPT1_OPTS}2>&1 | tee ${W_URL}/log/${ID}_mtDNApipe_$(date "+%Y%m%d-%H%M%S").out\n"
sh -e $mitoVGPdir/scripts/01_mtDNApipe -i ${ID} -r ${filename}.fasta -g ${GSIZE} -t ${NPROC} ${SCRIPT1_OPTS}2>&1 | tee ${W_URL}/log/${ID}_mtDNApipe_$(date "+%Y%m%d-%H%M%S").out &&

#identify the mitocontig
printf "\nCommand: sh -e $mitoVGPdir/scripts/02_blastMT -s ${SPECIES} -i ${ID} -r ${filename}.fasta 2>&1 | tee ${W_URL}/log/${ID}_blastMT_$(date "+%Y%m%d-%H%M%S").out\n"
sh -e $mitoVGPdir/scripts/02_blastMT -i ${ID} -r ${filename}.fasta 2>&1 | tee ${W_URL}/log/${ID}_blastMT_$(date "+%Y%m%d-%H%M%S").out

if [[ -z  ${CONTIG} ]]; then

	CONTIG_ID=$(cat ${W_URL}/blast/${ID%.*.*}_candidate_mitocontig.txt)

else

	CONTIG_ID=${CONTIG}

fi

if ! [[ -z  ${PLATFORM} ]]; then

	SCRIPT3_OPTS="${SCRIPT3_OPTS}-a ${PLATFORM} "

fi

if ! [[ -z  ${VAL} ]]; then

	SCRIPT3_OPTS="${SCRIPT3_OPTS}-v ${VAL} "

fi

if ! [[ -z  ${CAL} ]]; then

	SCRIPT3_OPTS="${SCRIPT3_OPTS}-b ${CAL} "

fi

#polish the mitocontig with long reads
printf "\nCommand: sh -e $mitoVGPdir/scripts/03_mitoPolish -s ${SPECIES} -i ${ID} -n ${CONTIG_ID} -t ${NPROC} ${SCRIPT3_OPTS} 2>&1 | tee ${W_URL}/log/${ID}_mitoPolish_$(date "+%Y%m%d-%H%M%S").out\n"
sh -e $mitoVGPdir/scripts/03_mitoPolish -i ${ID} -n ${CONTIG_ID} -t ${NPROC} ${SCRIPT3_OPTS} 2>&1 | tee ${W_URL}/log/${ID}_mitoPolish_$(date "+%Y%m%d-%H%M%S").out 

#polish the mitocontig with short reads
printf "\nCommand: sh -e $mitoVGPdir/scripts/04_map10x1 -s ${SPECIES} -i ${ID} -n ${CONTIG_ID} -t ${NPROC} ${SCRIPT4_OPTS} 2>&1 | tee ${W_URL}/log/${ID}_map10x1_$(date "+%Y%m%d-%H%M%S").out\n"
sh -e $mitoVGPdir/scripts/04_map10x1 -i ${ID} -n ${CONTIG_ID} -t ${NPROC} -2 ${IL} ${SCRIPT4_OPTS} 2>&1 | tee ${W_URL}/log/${ID}_map10x1_$(date "+%Y%m%d-%H%M%S").out || { echo "polishing with shortreads failed"; exit 1; }

if ! [[ -z  ${SEN} ]]; then

	SCRIPT5_OPTS="${SCRIPT5_OPTS}-z ${SEN} "

fi

#trim the mitocontig
printf "\nCommand: sh -e $mitoVGPdir/scripts/05_trimmer -s ${SPECIES} -i ${ID} -n ${CONTIG_ID} -t ${NPROC} ${SCRIPT5_OPTS} 2>&1 | tee ${W_URL}/log/${ID}_trimmer_$(date "+%Y%m%d-%H%M%S").out\n"
sh -e $mitoVGPdir/scripts/05_trimmer -i ${ID} -n ${CONTIG_ID} -t ${NPROC} ${SCRIPT5_OPTS} 2>&1 | tee ${W_URL}/log/${ID}_trimmer_$(date "+%Y%m%d-%H%M%S").out || { echo "trimming failed; trimming with MitoFinder"
	
	cp $(ls -t ${W_URL}/trimmed/*fasta | head -n 1) ${ID}/${ID}_prelim_MTcontig.fasta
	sh $mitoVGPdir/run_MitoFinder_annt.sh ${W_URL}/${ID}_prelim_MTcontig.fasta $ID
	
	printf "\n\nStarting QV analaysis on completed assemblies"
	sh $mitoVGPdir/submit_merqury.sh $ID
	
	exit 0;}

#polish the trimmed mitocontig with short reads
printf "\nCommand: sh -e $mitoVGPdir/scripts/06_map10x2 -s ${SPECIES} -i ${ID} -n ${CONTIG_ID} -t ${NPROC} 2>&1 | tee ${W_URL}/log/${ID}_map10x2_$(date "+%Y%m%d-%H%M%S").out\n"
sh -e $mitoVGPdir/scripts/06_map10x2 -i ${ID} -n ${CONTIG_ID} -t ${NPROC} 2>&1 | tee ${W_URL}/log/${ID}_map10x2._$(date "+%Y%m%d-%H%M%S").out &&

#perform final end trimming
printf "\nCommand: sh -e $mitoVGPdir/scripts/07_trimmer2 -s ${SPECIES} -i ${ID} -n ${CONTIG_ID} -t ${NPROC} 2>&1 | tee ${W_URL}/log/${ID}_trimmer2_$(date "+%Y%m%d-%H%M%S").out\n"
sh -e $mitoVGPdir/scripts/07_trimmer2 -i ${ID} -n ${CONTIG_ID} -t ${NPROC} 2>&1 | tee ${W_URL}/log/${ID}_trimmer2_$(date "+%Y%m%d-%H%M%S").out || \
	{ echo "trimmer2 failed; try trimming with MitoFinder"; 
        cp $(ls -t ${W_URL}/trimmed2/*.fasta | head -n 1) ${ID}/${ID}_trim2_prelim_MTcontig.fasta
	sh $mitoVGPdir/run_MitoFinder_annt.sh ${W_URL}/${ID}_trim2_prelim_MTcontig.fasta $ID 
	exit 0;}

cp ${W_URL}/trimmed2/${ID}.${CONTIG_ID}_polish2_10x1_trim1_10x2_trim2.fasta ${ID}_prelim_MTcontig.fasta
cp ${W_URL}/trimmed2/${ID}.${CONTIG_ID}_polish2_10x1_trim1_10x2_trim2.fasta qv/
printf "\n\nDone!"
printf "\n\nCompleted mitocontig assembly at: $(date "+%Y-%m-%d %H-%M-%S")\n\n"

printf "\n\nStarting mitofinder from trimmed 2x polished 2x mitocontig"
sh $mitoVGPdir/run_MitoFinder_annt.sh ${ID}_prelim_MTcontig.fasta $ID || \
{ printf "annotation with MitoFinder Failed"; exit 1; }
cp ${ID}/${ID}_MitoFinder_mitfi_Final_Results/${ID}_mtDNA_contig.fasta qv/

printf "\n\nStarting QV analaysis on completed assemblies"
#cp ${ID}_prelim_MTcontig.fasta qv/${ID}_prelim_MTcontig.fasta
sh $mitoVGPdir/submit_merqury.sh $ID

wait_file() {
  local file="$1"; shift

  until [ -f $file ] ; do sleep 300; done
  
}

wait_file qv/${ID}_mt_gt100.qv

sh $mitoVGPdir/summary.sh $ID > ${ID}_mito_summary_$(date "+%Y%m%d-%H%M%S").txt

printf "Done!! \n"
